### ISSUE TITLE
variantCaller not found in conda repos

### ISSUE THREAD

**Issue by nicolo-tellini** [RhettRautsaw/VariantCaller#1]
Dear @RhettRautsaw ,

I am installing a pipeline that make use of *variantCaller* although the installation of this software is not explained in the installer.
Following the pipeline scripts  *variantCaller* is supposed to be provided by one of the following conda packages: 

```
hdf5 v.1.10.6
pb-assembly v.0.0.8
bax2bam v.0.0.9
pbmm2 v.1.3.0
```
The installation succeeds but  *variantCaller* is not in the */bin/* and, following the installation is not even listed among the packages conda installs. 

Do you know if *variantCaller* was provided with one of the packages listed above and subsequently removed?

If the case, is it possible to provide a copy of  *variantCaller* version which was in conda at that time? 

thank you for your time,

best regards 

Nic

**Comment by RhettRautsaw** [comment]
Hi @nicolo-tellini. I'm not sure what pipeline uses VariantCaller. Could you point me in that direction so I can take a look? 

VariantCaller does not use `hdf5`, `pb-assembly`, `bax2bam`, or `pbmm2`. These programs are primarily used for PacBio data and VariantCaller is primarily designed to work with short-read Illumina data. This being said, as VariantCaller is just using the GATK and BCFTools best practices, so it should theoretically still work. 

As for installation of VariantCaller, it is not available via Anaconda and has never been on Anaconda unless someone else put it there. If you let me know what pipeline you are talking about, I might be able to check it out. VariantCaller is certainly not provided with any of the packages you listed. 

However, installation of VariantCaller is easy to do yourself! All the dependencies are probably already installed in your conda environment and if they are not, you should be able to install them via anaconda. After that, you simply need to clone this repository and add cloned folder to your PATH in your .bash_profile or .bashrc on Linux or .zshrc on Mac.

Hope this helps,

Rhett

**Comment by nicolo-tellini** [comment]
Hi @RhettRautsaw ,

Thank you for your reply.

Maybe, I am wrong ...

Installing  ```pb-assembly``` v. 0.0.3 with 

```
conda install -y -c bioconda pb-assembly=0.0.3
```

a function called variantCaller is also installed. 

I just noticed that it does not start with the "V" uppercase. 

and the helper looks like this : 

```
usage: variantCaller [-h] [--version] [--emit-tool-contract]
                     [--resolved-tool-contract RESOLVED_TOOL_CONTRACT]
                     [--log-file LOG_FILE]
                     [--log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL} | --debug | --quiet | -v]
                     --referenceFilename REFERENCEFILENAME -o OUTPUTFILENAMES
                     [-j NUMWORKERS] [--minConfidence MINCONFIDENCE]
                     [--minCoverage MINCOVERAGE]
                     [--noEvidenceConsensusCall {nocall,reference,lowercasereference}]
                     [--coverage COVERAGE] [--minMapQV MINMAPQV]
                     [--referenceWindow REFERENCEWINDOWSASSTRING]
                     [--alignmentSetRefWindows]
                     [--referenceWindowsFile REFERENCEWINDOWSASSTRING]
                     [--barcode _BARCODE] [--readStratum READSTRATUM]
                     [--minReadScore MINREADSCORE] [--minSnr MINHQREGIONSNR]
                     [--minZScore MINZSCORE] [--minAccuracy MINACCURACY]
                     [--algorithm {quiver,arrow,plurality,poa,best}]
                     [--parametersFile PARAMETERSFILE]
                     [--parametersSpec PARAMETERSSPEC]
                     [--maskRadius MASKRADIUS] [--maskErrorRate MASKERRORRATE]
                     [--pdb] [--notrace] [--pdbAtStartup] [--profile]
                     [--annotateGFF] [--reportEffectiveCoverage] [--diploid]
                     [--queueSize QUEUESIZE] [--threaded]
                     [--referenceChunkSize REFERENCECHUNKSIZE]
                     [--fancyChunking] [--simpleChunking]
                     [--referenceChunkOverlap REFERENCECHUNKOVERLAP]
                     [--autoDisableHdf5ChunkCache AUTODISABLEHDF5CHUNKCACHE]
                     [--aligner {affine,simple}] [--refineDinucleotideRepeats]
                     [--noRefineDinucleotideRepeats] [--fast]
                     [--skipUnrecognizedContigs]
                     inputFilename

Compute genomic consensus and call variants relative to the reference.

```
I can not find author info.

best,

Nic

**Comment by RhettRautsaw** [comment]
Yeah, this appears to be a function unrelated to my script. So I will close this. Good luck!
